apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017  #Sets port of service
      targetPort: 27017 #same as Containerport ,tell/forwards request to which port

#servuce and deployment will find each other via label Mongo

#Notes for User:
#Gives us the port number where container will listen 

# #Labels are for basically everything, you can label anything
# # Like a Added Identifiers, Used when we have multiple replicas
# of the pods. So basically Kube#rnetes gets to know which 
#pod belongs to which deployment we get that from the Matchlabels  
