apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
  spec:
    replicas: 1
    # tells the no of pods to be created
    selector:
      matchLabels:
        app: webapp
    template: #Config of Pod within the deployment
      metadata:
        labels:
          app: webapp
      spec:
        containers:
        - name: webapp
        image:  nanajanashia/K8s-demo-app:v1.0
        #The Docker image (DockerHub)
        ports:
        - containerPort: 3000 

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp 
  ports:
    protocol: TCP
    port: 3000  #Sets port of service
    targetPort: 3000 #same as Containerport ,tell/forwards request to which port